export const mockProfileData = {
      "login": "johnpapa",
      "id": 1202528,
      "node_id": "MDQ6VXNlcjEyMDI1Mjg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1202528?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/johnpapa",
      "html_url": "https://github.com/johnpapa",
      "followers_url": "https://api.github.com/users/johnpapa/followers",
      "following_url": "https://api.github.com/users/johnpapa/following{/other_user}",
      "gists_url": "https://api.github.com/users/johnpapa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/johnpapa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/johnpapa/subscriptions",
      "organizations_url": "https://api.github.com/users/johnpapa/orgs",
      "repos_url": "https://api.github.com/users/johnpapa/repos",
      "events_url": "https://api.github.com/users/johnpapa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/johnpapa/received_events",
      "type": "User",
      "site_admin": false,
      "name": "John Papa",
      "company": "JohnPapa.net, LLC",
      "blog": "http://johnpapa.net",
      "location": "Orlando, FL",
      "email": null,
      "hireable": null,
      "bio": "Winter is Coming",
      "twitter_username": "john_papa",
      "public_repos": 131,
      "public_gists": 56,
      "followers": 14150,
      "following": 0,
      "created_at": "2011-11-17T17:05:03Z",
      "updated_at": "2021-05-27T01:22:28Z"
  };
